### ISSUE TITLE
Port missing r(2+1)d 34-layer IG65-M model

### ISSUE THREAD

**Issue by daniel-j-h** [moabitcoin/ig65m-pytorch#3]
Blocked by official weights not being released so far:

https://github.com/facebookresearch/VMZ/issues/87

**Comment by sandhawalia** [comment]
The model [download](https://www.dropbox.com/s/eimo232tqw8mwi9/r2plus1d_34_clip32_ig65m_from_scratch_f102649996.pkl?dl=0) link is back up seems to be back up. The porting scripts are failing

```
python convert.py --frames 32 --classes 487 /nas/3rd_party/fair/video-model-zoo/VMZ-models-6c925c47b7d6545b64094a083f111258b37cbeca/r2plus1d_34_clip32_ig65m_from_scratch_f102649996.pkl /nas/team-space/experiments/video-ig65m/converted-models/r2plus1d_34_clip32_ig65m_from_scratch
Traceback (most recent call last):
  File "convert.py", line 204, in <module>
    main(parser.parse_args())
  File "convert.py", line 178, in main
    copy_fc(model.fc, blobs)
  File "convert.py", line 70, in copy_fc
    copy_tensor(module.bias.data, blobs, "last_out_L" + str(n) + "_b")
  File "convert.py", line 43, in copy_tensor
    tensor = torch.from_numpy(blobs[name])
KeyError: 'last_out_L487_b'
```

**Comment by sandhawalia** [comment]
Update. `r2plus1d_34_clip32_ig65m` is trained on 359 classes. Needs `359` as an option for `--classes` in `convert.py`

**Comment by sandhawalia** [comment]
https://github.com/moabitcoin/ig65m-pytorch/pull/10
